### PR TITLE
taxi/fly example with busy records

### LINKED ISSUE #247: Fly scans with taxi & fly busy records
There is a work-in-progress notebook ([`.wip/flyers/busy_fly_scan.ipynb`](https://github.com/BCDA-APS/bluesky_training/blob/main/.wip/flyers/busy_fly_scan.ipynb)) to demonstrate how to integrate the synApps taxi&fly scan algorithm into Bluesky.  Convert that into HOWTO documentation.

### PR DESCRIPTION
**Pull request by prjemian**
- close #247

### CODE REVIEW

**Comment by prjemian** [comment]
Might be more useful if added a second example using sscan record and collecting data.

**Comment by prjemian** [comment]
Also, this is more an example than a HOWTO.  Moving...

**Comment by prjemian** [comment]
[unit test failure](https://github.com/BCDA-APS/bluesky_training/actions/runs/6619635192/job/17980549611?pr=248):

```py
Run CMD="import ophyd"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/runner/micromamba/envs/anaconda-test-env-py-3.8/lib/python3.8/site-packages/ophyd/__init__.py", line 92, in <module>
    from .areadetector import *  # noqa: F401, F402, E402, F403
  File "/home/runner/micromamba/envs/anaconda-test-env-py-3.8/lib/python3.8/site-packages/ophyd/areadetector/__init__.py", line 7, in <module>
    from .base import *  # noqa: F401, F402, E402, F403
  File "/home/runner/micromamba/envs/anaconda-test-env-py-3.8/lib/python3.8/site-packages/ophyd/areadetector/base.py", line [22](https://github.com/BCDA-APS/bluesky_training/actions/runs/6619635192/job/17980549611?pr=248#step:12:23), in <module>
    import networkx as nx
  File "/home/runner/micromamba/envs/anaconda-test-env-py-3.8/lib/python3.8/site-packages/networkx/__init__.py", line 35, in <module>
    from networkx import generators
  File "/home/runner/micromamba/envs/anaconda-test-env-py-3.8/lib/python3.8/site-packages/networkx/generators/__init__.py", line 5, in <module>
    from networkx.generators.atlas import *
  File "/home/runner/micromamba/envs/anaconda-test-env-py-3.8/lib/python3.8/site-packages/networkx/generators/atlas.py", line 54, in <module>
    ATLAS_FILE = importlib.resources.files("networkx.generators") / "atlas.dat.gz"
AttributeError: module 'importlib.resources' has no attribute 'files'
Error: Process completed with exit code 1.
```

**Comment by prjemian** [comment]
Web search suggests an [answer](https://github.com/python-jsonschema/jsonschema/issues/921): `jsonschema >= 4 breaks conda`

Review these [reports](https://github.com/conda-forge/importlib_resources-feedstock/issues/46) that resolved this problem elsewhere.

**Comment by prjemian** [comment]
In this case, these versions:

```txt
2023-10-23T22:15:53.1899155Z   jsonschema                     4.19.1        pyhd8ed1ab_0            conda-forge
2023-10-23T22:15:53.1900357Z   jsonschema-specifications      2023.7.1      pyhd8ed1ab_0            conda-forge
2023-10-23T22:15:53.1901614Z   jsonschema-with-format-nongpl  4.19.1        pyhd8ed1ab_0            conda-forge
2023-10-23T22:15:53.2213870Z   python-fastjsonschema          2.18.1        pyhd8ed1ab_0            conda-forge
```

**Comment by prjemian** [comment]
Note the previous unit test failure did not recur.  Assume it was a transient problem.

**Comment by prjemian** [comment]
@MDecarabas @rodolakis - Finally, this is ready for review.

@cpchuang -- Preview the document at this URL: https://github.com/BCDA-APS/bluesky_training/blob/247-howto-busy-taxi-fly/docs/source/example/_busy_fly_scan.ipynb

**Comment by prjemian** [comment]
Seems more natural to override the `busy.trigger()` method instead of making a new `busy.set(v)` method where the `v` argument is ignored.

**Comment by prjemian** [comment]
This [CI error](https://github.com/BCDA-APS/bluesky_training/actions/runs/8351338281/job/22859513961?pr=248) seems transient.  Ignoring for now.

**Review by MDecarabas — APPROVED** [review]
LGTM!

**Pull request merged**
