### PR TITLE
home page should look friendlier

### LINKED ISSUE #283: Make installation checklist and installation guide header consistent
Some users were confused about the checklist at the top of the installation guide: should they follow checklist or the installation guide content? The wording of the TOC for the installation guide should be consistent with the working of the checklist, and ideally, the checklist link would link to the section from the installation guide (which can then refer to an external link).
The checklist most likely has the correct order of operation, so we should make the guide match the checklist (not the other way around).

### LINKED ISSUE #284: DOC: new instrument setup assistance
In the [checklist](https://bcda-aps.github.io/bluesky_training/instrument/_install_new_instrument.html#installation-checklist) (item _[initial configuration of instrument](https://bcda-aps.github.io/bluesky_training/instrument/_configure_bluesky_instrument.html#initial-configuration)_), needs to be a link to the [guidance for enabling device support](https://bcda-aps.github.io/bluesky_training/instrument/_configure_bluesky_instrument.html#devices).

Motivation is strong to resolve this issue. The existing docs are difficult for new users to follow at this point.

### LINKED ISSUE #285: DOC: Order of docs should be changed
In the various training documents, such as the [instrument](https://bcda-aps.github.io/bluesky_training/instrument/index.html) folder, some documents should appear earlier in the list, such as [Install New Instrument](https://bcda-aps.github.io/bluesky_training/instrument/_install_new_instrument.html).

### LINKED ISSUE #288: re-arrange the home page (of the web site)
The home page looks intimidating.  Especially to new users.  Make it prettier.  Here's some [advice](https://diataxis.fr/).

Compare with this draft of the bluesky-adaptive home page:
image

### LINKED ISSUE #295: What are the next steps after the initial installation?

### LINKED ISSUE #298: DOC: broken link
In this page: https://bcda-aps.github.io/bluesky_training/howto/_dynamic_limits_2motor.html#Create-a-suspender
this link is broken: https://blueskyproject.io/bluesky/state-machine.html#example-suspend-a-plan-if-the-beam-current-dips-low

### PR DESCRIPTION
**Pull request by prjemian**
- close #283
- close #284
- close #285
- close #288
- close #295
- close #298

### CODE REVIEW

**Comment by prjemian** [comment]
image

**Comment by prjemian** [comment]
Might get a lot easier if we add the [sphinx-design](https://sphinx-design.readthedocs.io/en/pydata-theme/get_started.html) package.

**Comment by prjemian** [comment]
(That's what bluesky-adaptive is using)

**Comment by prjemian** [comment]
Half the lines of code, no need for raw html, easier to manage.
image

**Comment by prjemian** [comment]
Download a preview copy of the web site for review from [docs actions](https://github.com/BCDA-APS/bluesky_training/actions/runs/8546687190) page.  The download is at/near the bottom of the page.

**Comment by rodolakis** [comment]
I actually find this a lot better - much less overwhelming. I can tell exactly where I want to go. I don't really see any value in the preview of "some" of the content. I'd rather just pick a category, and then browse from there. 

image

**Comment by prjemian** [comment]
image

**Comment by prjemian** [comment]
View of checklist now (text is pulled from the section title by Sphinx):

image

**Comment by prjemian** [comment]
One more step, at least, to modularize the content after the installation checklist.  See `TODO` items, such as https://github.com/BCDA-APS/bluesky_training/blob/dc30425bc9ce92a221f2d08e3b82e3bbcb1f74f5/docs/source/instrument/install_new_instrument.rst?plain=1#L22

**Comment by prjemian** [comment]
Published latest version to public website.

- home: https://bcda-aps.github.io/bluesky_training/
- checklist: https://bcda-aps.github.io/bluesky_training/instrument/install_new_instrument.html#instrument-install

Ready for review.

**Review by MDecarabas — COMMENTED** [review]
Home page looks great! The one change I would make to the new instrument setup is putting (optional) next to the steps that are not mandatory. Ie: creating an alias

**Comment by prjemian** [comment]
@MDecarabas -- re-examine the checklist: https://bcda-aps.github.io/bluesky_training/instrument/install_new_instrument.html#instrument-install

**Review by MDecarabas — APPROVED** [review]
Great!

**Comment by prjemian** [comment]
Thanks [MDecarabas](https://github.com/MDecarabas)!

**Comment by rodolakis** [comment]
Looks great!

**Pull request merged**
