### PR TITLE
new environment for 2024-3 cycle

### LINKED ISSUE #315: conda environment for 2024_3
- #259

### LINKED ISSUE #318: conda env create --force fails
User is following the installation instructions and creating a new conda environment.  This interaction:

```bash
(base) [user@host bluesky]$ conda env create --force -n bluesky_2023_3 -f ./environments/environment_2023_3.yml --solver=libmamba
usage: conda [-h] [-v] [--no-plugins] [-V] COMMAND ...
conda: error: unrecognized arguments: --force
```

### LINKED ISSUE #319: Installation instructions: environment file name out of date
User is installing per the installation checklist and encountered this error:

```bash
(base) [user@workstation bluesky]$ conda env create --force -n bluesky_2023_3 -f ./environments/environment_2023_3.yml --solver=libmamba

EnvironmentFileNotFound: '/path/to/bluesky/environments/environment_2023_3.yml' file not found
```

### PR DESCRIPTION
**Pull request by prjemian**
- close #315
- close #318
- close #319

### CODE REVIEW

**Comment by prjemian** [comment]
CI workflow failure from failed `ruff check`.  Also: `%run -i ~/bluesky/user/quick_hello.py` not found.

**Comment by prjemian** [comment]
Suspend `ruff` lint check for now.

**Comment by prjemian** [comment]
Also note the root level `environment.yml` file duplicates (somewhat) the content in `./bluesky/environments/environment*.yml`.  Maybe it should be much lighter, just what is necessary for this project and not a general run-time package environment for users?

**Comment by prjemian** [comment]
> Maybe ...should be much lighter...

This repo serves several purposes:

- documentation
- user training
- template for new installations at APS beamlines

As-is, the environment file provides a run-time suite of software supporting various user activities during and after data collection.  If any substantial changes now, make the project's `environment.yml` match the latest one in `./bluesky/environments/environment*.yml`.

**Comment by prjemian** [comment]
@rodolakis , @MDecarabas : Ready for review.  Can wait until we meet again.  Meanwhile, I will start using locally.

**Comment by prjemian** [comment]
[`README.md`](https://github.com/BCDA-APS/bluesky_training/blob/215-env-2024_3/bluesky/environments/README.md) needs to be updated.

**Review by MDecarabas — APPROVED** [review]

**Comment by prjemian** [comment]
@MDecarabas Thanks!

**Pull request merged**
