### PR TITLE
create unit tests for newSpecFile

### LINKED ISSUE #153: BUG newSpecFile() does not reset scan_id in RE.md
The test suite needs more cases to confirm.

### PR DESCRIPTION
**Pull request by prjemian**
- close #153

### CODE REVIEW

**Comment by prjemian** [comment]
Have not yet encountered the reported situation.

**Comment by prjemian** [comment]
This is ready for review.

- Unit tests were created for the existing `newSpecFile()` function.
- The behavior of the existing `newSpecFile()` function was documented with respect to existing SPEC file.
- The `newSpecFile()` function was refactored for readability, but same behavior as before, as assured by unit tests.

**Comment by rodolakis** [comment]
I would need a your help to understand that one.

**Comment by prjemian** [comment]
> I would need a your help to understand that one.

Unit testing is a new topic we should get into.  This PR might be that example that offers limited complexity yet real-world use.  The actual code changes in `bluesky/instrument/callbacks/spec_data_file_writer.py` are few.  The bulk of the new code consists of blocks which tests for the reported error and related capability.

What do you say if we leave this PR open and talk about it in an upcoming 1-on-1 meeting?

**Comment by prjemian** [comment]
You could test this branch and code yourself with this local command:

```bash
pytest -vvv --lf ./bluesky/tests/test_newSpecFile.py
```

**Pull request merged**
